service: quotosophy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

constructs:
  jobs:
    type: queue
    worker:
      handler: sqs\handler.consumer

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  producer:
    handler: handler.producer
    events:
      - httpApi:
          method: post
          path: /sqs/produce
          cors:
            origins:
              - http://api.quotosophy.com
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

custom:
  customDomain:
    domainName: api.quotosophy.com
    stage: dev
    certificateName: '*.quotosophy.com'
    createRoute53Record: true
    endpointType: 'edge'
    apiType: 'rest'
    securityPolicy: tls_1_2
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-webpack
  - serverless-lift

