org: lukejlackey
app: quotosophy
service: quotosophy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
