service: quotosophy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

functions:
  api:
    handler: handler.api
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  customDomain:
    domainName: api.quotosophy.com
    stage: dev
    certificateName: '*.quotosophy.com'
    createRoute53Record: true
    endpointType: 'edge'
    apiType: 'rest'
    securityPolicy: tls_1_2
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-webpack

